### ISSUE TITLE
Colab example?

### ISSUE THREAD

**Issue by asmith26** [jhejna/few-shot-preference-rl#4]
Hi there, this research looks really cool, so I thought I'd try run it via Google Colab but unfortunately I'm struggling. 

Note sure if you have already created a Colab example? I'm happy to give this a go if not (and if colab is powerful enough to run this of course). I think the main scripts/functions to try and get working are [`train`](https://github.com/jhejna/few-shot-preference-rl/blob/3182d020398578c625f25ae7d935aa1be7cca452/research/utils/trainer.py#L85) and [`visualize.py`](https://github.com/jhejna/few-shot-preference-rl/blob/main/scripts/visualize.py)?

Many thanks for any help, and many many thanks for this amazing research! :)

**Comment by jhejna** [comment]
Hi! Sorry I don't think I have the bandwidth to add this feature now. If you have developed a solution that works well let me know and I can reference it for others who might be interested.
