### ISSUE TITLE
The research installation package is missing

### ISSUE THREAD

**Issue by ZlSong417** [jhejna/few-shot-preference-rl#6]
(few-shot-pref-rl) root@interactive28332:~/few-shot-preference-rl-main/scripts# python visualize.py
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libGLEW.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Traceback (most recent call last):
  File "visualize.py", line 7, in <module>
    from research.utils.config import Config
ModuleNotFoundError: No module named 'research'

**Comment by jhejna** [comment]
You need to run `pip install -e .` to install the package.
